language: python

install:
    - pip install -r requirements/base.txt
    - pip install -r requirements/test.txt

script:
    - pylint django_mysql_retry_init
    - pycodestyle django_mysql_retry_init
    - echo "import django_mysql_retry_init" > meow.py
    - coverage run --source=django_mysql_retry_init --branch meow.py

after_success:
    coveralls

notifications:
      email: false
