language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6

cache: pip

env:
    - TOXENV=django18
    - TOXENV=django110
    - TOXENV=django111

matrix:
    exclude:
    - python: 3.6
      env: TOXENV=django18
    - python: 3.3
      env: TOXENV=django110
    - python: 3.6
      env: TOXENV=django110
    - python: 3.3
      env: TOXENV=django111
    include:
    - python: 3.6
      env: TOXENV=quality

install:
    - pip install -r requirements/test.txt

script: tox
after_success: coveralls

notifications:
      email: false
